#pragma once

#include "cfcoef.h"
#include "cfcopy.h"
#include "cfdiag.h"
#include "cfexact.h"
#include "cfgen.h"
#include "cfinit.h"
#include "cfinteraction.h"
#include "cfjacobydiag.h"
#include "cfjacobymultdirect.h"
#include "cfjacobyreduce.h"
#include "cfjacobyupdate.h"
#include "cfjacobyupdaterecv.h"
#include "cfjacobyupdatesend.h"
#include "cfloadpoints.h"
#include "cfloadtriangles.h"
